version: "3"
services:
  flask:
    build: ./dockerz
    container_name: flask
    restart: always
    expose:
      - 5000
  nginx:
    build: ./dockerz/dock
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
